name = "CoordinatedMotionPlanning"
uuid = "2c19330b-8a26-459f-bb5f-3c648cf4fc23"
authors = ["Saujas Nandi"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
